origins: 
  # - "$HOME/Library/Preferences/com.viscosityvpn.Viscosity.plist"
  - "$HOME/dotfiles/misc"
  - "$HOME/.tether"


destinations: 
  - "/tmp/.tst"
  - "/tmp/.tst1"


options:
  - encrypt
  - zip

# check list of destinations
# if none available, exit
# option to zip
# option to encrypt
# restore puts stuff back where it got them from
# bck -encrypt -zip

# sanity check don't check origins for restore