origins: 
  # - "$HOME/Library/Preferences/com.viscosityvpn.Viscosity.plist"
  - "/tmp/origins/a"
  - "/tmp/origins/b"


destinations: 
  - "/tmp/destinations/1"
  - "/tmp/destinations/2"


options:
  - encrypt
  - zip

# check list of destinations
# if none available, exit
# option to zip
# option to encrypt
# restore puts stuff back where it got them from
# bck -encrypt -zip

# sanity check don't check origins for restore
# add mkdir check to destinations